name: rufus
version: '1.0'
summary: Logiciel d'Ophtalmologie.
description: Logiciel de gestion de cabinet d'Ophtalmologie.
type: app
grade: devel
confinement: classic
base: core18

apps:
 rufus:
    command: usr/bin/rufus
    plugs: [desktop, home, x11, network, wayland, serial-port, raw-usb]
    desktop: ./Rufus.AppDir/rufus.desktop
 
parts:
    
 poppler-data:
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-data-0.4.9.tar.gz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++-7]
    build-packages:
      - cmake
      - gcc

 poppler:
    after: [poppler-data]
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-0.74.0.tar.xz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++-7]
    build-packages:
      - gcc
      - cmake
      - libyelp-dev                    
      - libopenjp2-7-dev
      - poppler-data
      - libpoppler-glib-dev
      - yelp-tools
      - libsecret-1-dev
      - libnautilus-extension-dev
      - libpulse-dev
      - libpulse-mainloop-glib0 
      - poppler-utils
      - libnss3-dev
      - libjpeg-dev

 rufus:
    after: [poppler-data, poppler]
    source: .
    plugin: qmake
    project-files: [snapcraft.pro]
    organize:
        opt/rufus/bin: bin
    build-packages:
      - gcc
      - libqt5sql5-mysql
      - dirmngr
      - build-essential
      - qt5-default
      - qtmultimedia5-dev
      - libqt5serialport5-dev
