name: rufus
version: '1.0'
summary: Logiciel d'Ophtalmologie.
description: Logiciel de gestion de cabinet d'Ophtalmologie.
type: app
grade: devel
confinement: classic

apps:
 rufus:
    command: usr/bin/rufus
    plugs: [desktop, home, x11, network, wayland, serial-port, raw-usb]
    desktop: ./Rufus.AppDir/rufus.desktop
 
parts:
 qt:
    after: [gcc7, poppler-data, poppler]
    plugin: qtbuilder
    qt-version: 5.10.0
    qt-source-git: https://code.qt.io/qt/qt5.git
    qt-submodules: ['qtbase', 'qtmultimedia', 'qtserialport']
    environment:
      - CC: gcc-7
      - CXX: g++-7
      - QMAKE_CC: gcc-7
      - QMAKE_CXX: g++-7
    build-packages:
      - libasound2-dev
      - libdbusmenu-glib-dev
      - libffi-dev
      - liblzma-dev
      - libpulse-dev
      - libssl-dev
      - libx11-xcb-dev
      - libxcb-icccm4-dev
      - libxcb-image0-dev
      - libxcb-keysyms1-dev
      - libxcb-randr0-dev
      - libxcb-render-util0-dev
      - libxcb-sync-dev
      - libxcb-util0-dev
      - libxcb-xfixes0-dev
      - libxcb1-dev
      - libxrender-dev
    configflags:
      - -prefix
      - $SNAPCRAFT_STAGE
      - -release
      - -force-debug-info
      - -opensource
      - -confirm-license
      - -qt-zlib
      - -qt-libpng
      - -qt-libjpeg
      - -qt-freetype
      - -qt-harfbuzz
      - -qt-pcre
      - -qt-xcb
      - -qt-xkbcommon-x11
      - -no-gstreamer
      - -no-gtkstyle
      - -no-mirclient
      - -no-opengl
      - -static
      - -dbus-runtime
      - -openssl-linked
      - -nomake
      - examples
      - -nomake
      - tests
    
 gcc7:
    plugin: nil
    build-packages:
      - libmpc-dev
      - libcloog-ppl-dev
    override-pull: |
      echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" | \
            sudo tee /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 60C317803A41BA51845E371A1E9377A2BA9EF27F
      sudo apt-get update \
        -o Dir::Etc::sourcelist="sources.list.d/ubuntu-toolchain-r.list" \
        -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
      snapcraftctl pull
    override-build: |
      sudo apt install gcc-7 g++-7 -o Debug::pkgProblemResolver=yes --no-install-recommends -y
      sudo apt-mark auto gcc-7 g++-7
      sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      snapcraftctl build

 poppler-data:
    after: [gcc7]
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-data-0.4.9.tar.gz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release]
    build-packages:
      - build-essential
      - cmake

 poppler:
    after: [gcc7, poppler-data]
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-0.67.0.tar.xz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release]
    build-packages:
      - build-essential
      - cmake
      - libyelp-dev            
      - libopenjpeg-dev        
      - libopenjp2-7-dev
      - poppler-data
      - libpoppler-glib-dev
      - yelp-tools
      - libsecret-1-dev
      - libnautilus-extension-dev
      - libpulse-dev
      - libpulse-mainloop-glib0 
      - poppler-utils
      - libnss3-dev
      - libjpeg-dev

 rufus:
    after: [qt, gcc7, poppler-data, poppler]
    plugin: qmake
    project-files: [snapcraft.pro]
    organize:
        opt/rufus/bin: bin
    build-packages:
      - libpoppler-qt5-dev
      - libqt5sql5-mysql
