name: rufus
version: '1.0'
summary: Logiciel d'Ophtalmologie.
description: Logiciel de gestion de cabinet d'Ophtalmologie.
type: app
grade: devel
confinement: classic

apps:
 rufus:
    command: usr/bin/rufus
    plugs: [desktop, home, x11, network, wayland, serial-port, raw-usb]
    desktop: ./Rufus.AppDir/rufus.desktop
 
parts:
    
 gcc7:
    plugin: nil
    build-packages:
      - libmpc-dev
      - libcloog-ppl-dev
    override-pull: |
      echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" | \
            sudo tee /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 60C317803A41BA51845E371A1E9377A2BA9EF27F
      sudo apt-get update \
        -o Dir::Etc::sourcelist="sources.list.d/ubuntu-toolchain-r.list" \
        -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
      snapcraftctl pull
    override-build: |
      sudo apt install gcc-7 g++-7 -o Debug::pkgProblemResolver=yes --no-install-recommends -y
      sudo apt-mark auto gcc-7 g++-7
      sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r.list
      snapcraftctl build

 poppler-data:
    after: [gcc7]
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-data-0.4.9.tar.gz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++-7]
    build-packages:
      - cmake

 poppler:
    after: [gcc7, poppler-data]
    plugin: cmake
    source: https://poppler.freedesktop.org/poppler-0.70.1.tar.xz
    source-type: tar
    configflags: [-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/usr/bin/g++-7]
    build-packages:
      - cmake
      - libyelp-dev                    
      - libopenjp2-7-dev
      - poppler-data
      - libpoppler-glib-dev
      - yelp-tools
      - libsecret-1-dev
      - libnautilus-extension-dev
      - libpulse-dev
      - libpulse-mainloop-glib0 
      - poppler-utils
      - libnss3-dev
      - libjpeg-dev

 rufus:
    after: [desktop-qt5, gcc7, poppler-data, poppler]
    plugin: qmake
    project-files: [snapcraft.pro]
    build-packages:
      - libqt5sql5-mysql
      - dirmngr
      - build-essential
      - qt5-default
      - qtmultimedia5-dev
      - libqt5serialport5-dev
